module.exports={
USER_COLLECTION:'users',
ADMIN_COLLECTION:'admin',
PRODUCT_COLLECTION:'product',
CATEGORY_COLLECTION:'category',
CART_COLLECTION:'Cart',
ORDER_COLLECTION:'order',
WISHLIST_COLLECTION:"wishlist",
BANNER_COLLECTION: 'banner',
WALLET_COLLECTION: 'wallet',
COUPON_COLLECTION: 'coupon'
}
